---
title: "Análisis Datos Ómicos" 
subtitle: "Segunda Prueba de Evaluación Contínua"
author: "Jairo Aguirre Bedoya"
date: "22/12/2024"
output: 
    html_document:
         code_foldinf: hide
         toc: true
         toc_depth: 3
         theme: journal
         highlight: textmate
         number_sections: true
editor_options:
 chunk_output_type: console
---

Lo primero que haremos será definir los directorios donde se almacenarán los datos y los resultados del análisis.

```{r directorios}
workingDir <-getwd()
dataDir <- file.path(workingDir, "datos")
resultsDir <- file.path(workingDir, "resultados")
```

Procedemos a instalar los paquetes necesarios para nuestro análisis

```{r paquetes, message = FALSE, warning = FALSE, results = "hide"}

if (!requireNamespace("BiocManager", quietly = TRUE)) {
  install.packages("BiocManager")
}

installifnot <- function(pkg) {
  if (!require(pkg, character.only = TRUE)) {
    BiocManager::install(pkg)
  }
}

paquetes <- c(
  "pd.mogene.2.1.st", "mogene21sttranscriptcluster.db", "oligo", "limma", 
  "Biobase", "arrayQualityMetrics", "genefilter", "annotate", "xtable", 
  "gplots", "GOstats", "knitr", "colorspace", "ggplot2", "ggrepel", 
  "htmlTable", "prettydoc", "devtools", "pvca", "org.Mm.eg.db", 
  "ReactomePA", "reactome.db"
)

lapply(paquetes, installifnot)
```

